packages:
  - "packages/*"

catalogs:
  tooling:
    "@yopem/eslint-config": ^0.1.4
    "@yopem/prettier-config": ^0.1.1
    "@yopem/typescript-config": ^0.1.0
    eslint: ^9.21.0
    prettier: ^3.5.3
    tailwindcss: ^4.0.2
    tsup: ^8.3.6
    typescript: ^5.7.3
