name: Publish Any Commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish './packages/*'
